version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8010:8010"
    env_file:
      - ./.env
    depends_on:
      - mongo_db
      
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo_db

  question-service:
    build:
      context: ./question-service
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    depends_on:
      - mongo_db

  matching-service:
    build:
      context: ./matching-service
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - mongo_db

  collaboration-service:
    build:
      context: ./collaboration-service
    ports:
      - "8004:8004"
    env_file:
      - ./.env
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: cs3219_project
    volumes:
      - ./mongo-seed/:/docker-entrypoint-initdb.d/
      - mongo_db_vol:/data/db

volumes:
  mongo_db_vol: